### PR TITLE
Russian localisation for hoi4modutilities

### PR DESCRIPTION
**Pull request by Ivan-Corporation**
Hi! I'm impressed with your mod and decide to help with russian localisation (I'm native russian speaker and with auto translate most of sentences don't have sense at all^) 
i18next really nice choice for localisation and if you want, i can help with future localisation when more great functions will be ready coz i'm already starred repo :)

### CODE REVIEW

**Comment by herbix** [comment]
Thank you, @Ivan-Corporation!
There's another i18n related file: https://github.com/herbix/hoi4modutilities/blob/master/i18n/template.ts
Are you going to translate it too?

**Comment by Ivan-Corporation** [comment]
Oh, yeah of course, i'm just thought that it is some future logic. I'm translated sites only on json format)
I'm think i will translate it today, this repo is really helpful and how i know game really popular in Russia, so it's be really useful to have full translation

**Comment by Ivan-Corporation** [comment]
well it was not so easy but ru.ts is ready. I hope i can help in future too

**Comment by herbix** [comment]
@Ivan-Corporation It's late for me now. I'll create a new version containing your translation tomorrow.

**Pull request merged**
